<?php

// Generated by ZF2's ./bin/classmap_generator.php

return array(
    'TwwSaml\Adapter\Saml'                      => __DIR__ . '/../../src/TwwSaml/Adapter/Saml.php',
    'TwwSaml\Controller\AcsController'          => __DIR__ . '/../../src/TwwSaml/Controller/AcsController.php',
    'TwwSaml\Controller\MetadataController'     => __DIR__ . '/../../src/TwwSaml/Controller/MetadataController.php',
    'TwwSaml\Entity\User'                       => __DIR__ . '/../../src/TwwSaml/Entity/User.php',
    'TwwSaml\Module'                            => __DIR__ . '/../../src/TwwSaml/Module.php',
    'TwwSaml\ServiceFactory\SamlAdapterFactory' => __DIR__ . '/../../src/TwwSaml/ServiceFactory/SamlAdapterFactory.php',
    'TwwSaml\ServiceFactory\SamlConfigFactory'  => __DIR__ . '/../../src/TwwSaml/ServiceFactory/SamlConfigFactory.php',
);
